pipeline {

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git url:'https://github.com/rushabhmahale/hellowhale.git', branch:'master'
      }
    }
    stage('List pods') {
      steps {
        withKubeConfig([credentialsId: 'mykubeconfig',
                        caCertificate: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1Ea3hNekEzTXpZeE9Wb1hEVE14TURreE1qQTNNell4T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkhBCjN1a3JOdVlzV3M2UEZ1LzVTSnFFNkJsWUlaWGJTQzZnSzgxVVJLb3M5VG4raGtHNWF3dGtLVlpyZVg5RDZGUjkKaHE4bFd3NmZMK2t4TG9OdFNSOU9PSFprUmdCN2tUaTZTLzNrQUpHVVhGTytINzd5eDUvZlpsc3E2WEU5RmRVZgpZMVlST3kydVFrQWNFOGxWOEoxNzlYUlRCNHhoeFJXV08zaitvSjNpeHY0R2FydmY1N05maVh1UFFudU53SVZpCkJzU0xuaEMwZmpYMU51WXIvQ2lpSzNQSXhaZVlWTm5OZmF1WnNZMk94M1lOaEJjMHlUeWxFSXh3TlQzbFZWbHkKNzBVTWZDNnhXbU1HZW9TeCsraUx0T2pQZ0JtSW1iWjFjc0owQ2hlUEo5TTZTYVRqMWpONGxHODVtbWhwcmZPZAo2RjVrM2l2b1MwUis4L1FVRXFVQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSc0Eydzl0RzFZMG9GYkdCUHZpaFZxVUNNVURqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF2Y1RrSXc1NwpYaEF3VVNqMTZiNHQvMG1GRUx2dUxGSWVYMmFmdWlqV0Zpb0U3UWgwb2YxVlBSU0xsUnpyNUc4M2FwUVpVRGNiCjBVdDNYRk9TSEhLSHc2RnJSOHBuYXA5cmJSY2RERFFoYXpyZVNLWlQ0TWJPbXJYRXN0Q3UwbGdIbkxJdXB5NEkKMGpRNTA1YU40VHdSTUhYUlVOWTN1bEZObUZkNEZ5VlArY201YVlJdEJMenFxbStuTU5KaWloQy9zOGtvSzFoLwpDRzdRdlNoUzdieUpKemNiOUp5SEVkN21kWlZBSGpFdkNQR2IydVVKT3RSSHlIdkVOTUVYdWY0ZWE0ZTZ3NXVpCnVKRk1vMllqZExVUCtXZ1lncm1Pc0huL3RYNTZ1STJlamwrczZTQnlYVXFEdnlnQmFSeWQ1T0hwYmE0Q3NVMlQKcFRnRFY5b2UrUnlVZlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==',
                    serverUrl: 'https://192.168.99.100:8443',
                    clusterName: 'minikube',
                    namespace: 'default'
                    ]) {
      sh 'kubectl get pods'
      }
    }
   }
  }
}
